import { DEFAULT_ELEMENTS, DEFAULT_ORIGIN, DEFAULT_PARAMS } from "./constants";
import { defaultIntervention } from "./interventions";
import { normalizeParams } from "./planet";
import type {
  Atmosphere, ElementalBasis, OriginConfig, PlannedIntervention, ScenarioConfiguration,
  ScenarioDefinition, ScientificSource
} from "./types";

export const SCIENCE_SOURCES: Record<string, ScientificSource> = {
  "kopparapu-2014": { id: "kopparapu-2014", title: "Habitable Zones Around Main-sequence Stars", attribution: "Kopparapu et al.", year: 2014, url: "https://doi.org/10.1088/0004-637X/787/2/29", kind: "primary" },
  "catling-zahnle-2020": { id: "catling-zahnle-2020", title: "The Archean atmosphere", attribution: "Catling & Zahnle", year: 2020, url: "https://doi.org/10.1126/sciadv.aax1420", kind: "review" },
  "pearce-2017": { id: "pearce-2017", title: "Origin of the RNA world in warm little ponds", attribution: "Pearce et al.", year: 2017, url: "https://doi.org/10.1073/pnas.1710339114", kind: "primary" },
  "sojo-2016": { id: "sojo-2016", title: "The origin of life in alkaline hydrothermal vents", attribution: "Sojo et al.", year: 2016, url: "https://doi.org/10.1089/ast.2015.1406", kind: "review" },
  "cleaves-2008": { id: "cleaves-2008", title: "A reassessment of prebiotic organic synthesis in neutral planetary atmospheres", attribution: "Cleaves et al.", year: 2008, url: "https://doi.org/10.1007/s11084-007-9120-3", kind: "primary" },
  "lambert-2010": { id: "lambert-2010", title: "Mineral surfaces and the prebiotic chemistry of early Earth", attribution: "Lambert", year: 2010, url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC2857174/", kind: "review" },
  "attwater-2010": { id: "attwater-2010", title: "Ice as a protocellular medium for RNA replication", attribution: "Attwater et al.", year: 2010, url: "https://doi.org/10.1038/ncomms1076", kind: "primary" },
  "deamer-2012": { id: "deamer-2012", title: "Role of amphiphilic compounds in the evolution of membrane structure", attribution: "Deamer", year: 2012, url: "https://doi.org/10.1089/ast.2011.0721", kind: "review" },
  "callahan-2011": { id: "callahan-2011", title: "Carbonaceous meteorites contain a wide range of extraterrestrial nucleobases", attribution: "Callahan et al.", year: 2011, url: "https://doi.org/10.1073/pnas.1106493108", kind: "primary" },
  "carr-2020": { id: "carr-2020", title: "The potential for lithopanspermia in the TRAPPIST-1 system", attribution: "Krijt et al.", year: 2017, url: "https://doi.org/10.3847/1538-4357/aa7a43", kind: "primary" },
  "cukier-2019": { id: "cukier-2019", title: "Habitable Zone Boundaries for Circumbinary Planets", attribution: "Cukier et al.", year: 2019, url: "https://arxiv.org/abs/1911.02983", kind: "primary" },
  "kane-2013": { id: "kane-2013", title: "Habitable Zones of Circumbinary Planetary Systems", attribution: "Kane & Hinkel", year: 2013, url: "https://arxiv.org/abs/1211.2812", kind: "primary" },
  "madhusudhan-2021": { id: "madhusudhan-2021", title: "Habitability and Biosignatures of Hycean Worlds", attribution: "Madhusudhan et al.", year: 2021, url: "https://doi.org/10.3847/1538-4357/abfd9c", kind: "primary" },
  "pierrehumbert-2011": { id: "pierrehumbert-2011", title: "Hydrogen Greenhouse Planets Beyond the Habitable Zone", attribution: "Pierrehumbert & Gaidos", year: 2011, url: "https://doi.org/10.1088/2041-8205/734/1/L13", kind: "primary" },
  "arney-2016": { id: "arney-2016", title: "The Pale Orange Dot: The Spectrum and Habitability of Hazy Archean Earth", attribution: "Arney et al.", year: 2016, url: "https://doi.org/10.1089/ast.2015.1422", kind: "primary" }
};

const anoxic: Atmosphere = { n2: .78, co2: .14, h2o: .025, ch4: .018, o2: .0001, h2: .025, nh3: .001, so2: .0109 };
const reducing: Atmosphere = { n2: .51, co2: .08, h2o: .07, ch4: .15, o2: .0001, h2: .16, nh3: .022, so2: .0079 };
const h2Rich: Atmosphere = { n2: .18, co2: .04, h2o: .025, ch4: .035, o2: .0001, h2: .715, nh3: .003, so2: .0019 };
const methaneRich: Atmosphere = { n2: .71, co2: .012, h2o: .002, ch4: .225, o2: .0001, h2: .045, nh3: .004, so2: .0019 };

const carbonRich: ElementalBasis = { ...DEFAULT_ELEMENTS, carbon: .94, oxygen: .34, phosphorus: .12, sulfur: .62, iron: .55 };
const ironSulfurRich: ElementalBasis = { ...DEFAULT_ELEMENTS, carbon: .31, phosphorus: .11, sulfur: .92, iron: .94 };
const comet = (age: number, magnitude = .55): PlannedIntervention => {
  const value = defaultIntervention("ice-comet", age, 1);
  return { type: value.type, label: value.label, scheduledAgeMyr: age, magnitude, cargo: value.cargo };
};
const organics = (age: number, magnitude = .6): PlannedIntervention => {
  const value = defaultIntervention("organic-asteroid", age, 1);
  return { type: value.type, label: value.label, scheduledAgeMyr: age, magnitude, cargo: value.cargo };
};

const baseEarlyEarth = {
  starMassSolar: 1, starLuminositySolar: .75, starTemperatureK: 5650, starActivity: .58, starAgeGyr: .55,
  orbitalDistanceAu: 1, orbitalEccentricity: .025, planetMassEarth: 1, planetRadiusEarth: 1,
  rotationHours: 15, axialTiltDeg: 23, albedo: .27, waterInventory: .76, landFraction: .17,
  coreFraction: .33, mantleFraction: .65, initialHeat: .91, radionuclides: .78, tectonicMobility: .72,
  impactRate: .62, atmospherePressureBar: 1.15, atmosphere: anoxic, elementBasis: DEFAULT_ELEMENTS,
  mutationRate: .42, originDifficulty: .64
} satisfies Partial<typeof DEFAULT_PARAMS>;

const scenario = (value: Omit<ScenarioDefinition, "schemaVersion" | "modelVersion">): ScenarioDefinition => ({ schemaVersion: 1, modelVersion: "1.1", ...value });

export const SCENARIO_PRESETS: ScenarioDefinition[] = [
  scenario({ id: "hadean-cooling", label: "Hadean cooling analogue", subtitle: "4.4–4.1 Ga hypothesis bracket", description: "A hot, impact-rich young Earth analogue with a faint young Sun, small emergent land fraction, an anoxic volatile envelope, and strong interior activity.", category: "earth-history", evidence: "coarse", modelFit: "native", confidenceNote: "Major reservoirs are plausible brackets, not a reconstruction of one known Hadean atmosphere.", tags: ["early Earth", "anoxic", "impact-rich"], sourceIds: ["catling-zahnle-2020", "kopparapu-2014"], caveats: ["Hadean surface pressure and reducing-gas abundance remain poorly constrained.", "The magma-ocean interval is compressed into initial conditions."], params: { ...baseEarlyEarth, starLuminositySolar: .72, starAgeGyr: .18, starActivity: .82, rotationHours: 12, waterInventory: .58, landFraction: .055, initialHeat: .98, impactRate: .9, atmospherePressureBar: 1.6, atmosphere: { ...anoxic, co2: .22, n2: .70, h2: .035 } }, origin: { theory: "hydrothermal", ventFlux: .84, wetDryCycling: .12, energy: .7 }, interventions: [comet(35, .7), organics(80, .55)] }),
  scenario({ id: "late-hadean-shore", label: "Late-Hadean shore analogue", subtitle: "Wet–dry concentration opportunity", description: "An uncertainty-bracketed anoxic coastline with exposed volcanic land, rainfall-fed ponds, ultraviolet energy, and recurring impact delivery.", category: "earth-history", evidence: "coarse", modelFit: "native", confidenceNote: "Local wet–dry environments are plausible; their prevalence and exact chemistry are uncertain.", tags: ["early Earth", "shoreline", "RNA world"], sourceIds: ["pearce-2017", "catling-zahnle-2020", "callahan-2011"], caveats: ["RNA-world chemistry is represented by gate scores rather than reaction kinetics."], params: baseEarlyEarth, origin: { theory: "pond", energy: .74, catalysts: .62, wetDryCycling: .9, exogenousDose: .38, recurrence: .5 }, interventions: [organics(20, .65), organics(180, .42)] }),
  scenario({ id: "eoarchean-vents", label: "Eoarchean vent analogue", subtitle: "Alkaline-gradient hypothesis", description: "A deep-ocean early-Earth analogue with vigorous water–rock reactions, mineral pores, sustained redox gradients, and limited dry land.", category: "earth-history", evidence: "coarse", modelFit: "native", confidenceNote: "Vent gradients are physically grounded; the path from geochemistry to heredity remains unresolved.", tags: ["early Earth", "hydrothermal", "metabolism-first"], sourceIds: ["sojo-2016", "catling-zahnle-2020"], caveats: ["Vent microstructure and proton gradients are compressed into global indices."], params: { ...baseEarlyEarth, starAgeGyr: .72, starLuminositySolar: .77, waterInventory: .98, landFraction: .07, tectonicMobility: .84, initialHeat: .86, atmospherePressureBar: 1.3 }, origin: { theory: "hydrothermal", energy: .68, catalysts: .92, wetDryCycling: .04, ventFlux: .98 }, interventions: [] }),
  scenario({ id: "archean-haze", label: "Archean organic-haze analogue", subtitle: "Methane-cycle climate experiment", description: "An anoxic Earth analogue with biologically agnostic methane forcing and a photochemical haze proxy under the faint young Sun.", category: "earth-history", evidence: "coarse", modelFit: "proxy", confidenceNote: "Haze radiative effects are represented coarsely through atmosphere and albedo controls.", tags: ["early Earth", "methane", "haze"], sourceIds: ["arney-2016", "catling-zahnle-2020"], caveats: ["The model does not resolve aerosol particle chemistry or spectral opacity."], params: { ...baseEarlyEarth, starAgeGyr: .95, starLuminositySolar: .79, starActivity: .42, atmosphere: { ...anoxic, n2: .735, co2: .095, ch4: .095 }, albedo: .34 }, origin: { theory: "atmospheric", energy: .78, catalysts: .42 }, interventions: [] }),

  scenario({ id: "spark-wet-dry-rna", label: "Spark: wet–dry RNA cycles", subtitle: "Surface concentration + heredity-first", description: "Cycles dissolved precursors through concentration, polymerization, rehydration, and dispersal opportunities in warm volcanic ponds.", category: "plausible", evidence: "coarse", modelFit: "native", confidenceNote: "Experiments support useful reaction steps; no complete abiogenesis route has been demonstrated.", tags: ["origin theory", "RNA", "wet–dry"], sourceIds: ["pearce-2017"], caveats: ["The model treats heredity as a probabilistic gate."], params: baseEarlyEarth, origin: { theory: "rna-first", energy: .72, catalysts: .65, wetDryCycling: .96, ventFlux: .12 }, interventions: [] }),
  scenario({ id: "spark-alkaline-vents", label: "Spark: alkaline vents", subtitle: "Redox gradients + metabolism-first", description: "Explores mineral membranes, natural electrochemical gradients, catalytic transition metals, and continuous reactant flow.", category: "plausible", evidence: "coarse", modelFit: "native", confidenceNote: "Geochemical energy is plausible; emergence of genetic heredity is still speculative.", tags: ["origin theory", "vents", "metabolism"], sourceIds: ["sojo-2016"], caveats: ["Global vent flux is not a fluid-dynamics calculation."], params: { ...baseEarlyEarth, waterInventory: 1.05, landFraction: .04, tectonicMobility: .88 }, origin: { theory: "hydrothermal", energy: .7, catalysts: .93, wetDryCycling: .02, ventFlux: .98 }, interventions: [] }),
  scenario({ id: "spark-atmospheric", label: "Spark: ultraviolet network", subtitle: "Photochemistry + cyanosulfidic proxy", description: "Tests ultraviolet and electrical feedstock production followed by rainout and concentration in surface reservoirs.", category: "plausible", evidence: "coarse", modelFit: "native", confidenceNote: "Organic synthesis is experimentally supported; yields depend strongly on uncertain gas composition and wavelength.", tags: ["origin theory", "lightning", "ultraviolet"], sourceIds: ["cleaves-2008"], caveats: ["This deliberately reducing atmosphere is a chemistry experiment, not the early-Earth consensus.", "The engine does not resolve wavelength-dependent photochemistry."], params: { ...baseEarlyEarth, atmosphere: reducing, atmospherePressureBar: 1.25, landFraction: .23 }, origin: { theory: "uv-network", energy: .96, catalysts: .58, wetDryCycling: .62 }, interventions: [] }),
  scenario({ id: "spark-mineral-template", label: "Spark: mineral templates", subtitle: "Adsorption + surface catalysis", description: "Uses clays, metal sulfides, and other reactive surfaces as concentration and organization proxies.", category: "plausible", evidence: "speculative", modelFit: "native", confidenceNote: "Individual catalytic effects are grounded; a full templated path to life is not established.", tags: ["origin theory", "minerals", "catalysis"], sourceIds: ["lambert-2010"], caveats: ["Mineral diversity is compressed into one catalyst control."], params: { ...baseEarlyEarth, landFraction: .34, waterInventory: .54, tectonicMobility: .78, elementBasis: ironSulfurRich }, origin: { theory: "mineral-template", energy: .55, catalysts: .98, wetDryCycling: .68 }, interventions: [] }),
  scenario({ id: "spark-lipid-first", label: "Spark: lipid-first", subtitle: "Compartments before robust heredity", description: "Favors amphiphile assembly, encapsulation, osmotic cycling, and selection among protocell-like compartments.", category: "plausible", evidence: "speculative", modelFit: "native", confidenceNote: "Self-assembly is grounded; coupling compartments to replication remains an open problem.", tags: ["origin theory", "lipids", "protocells"], sourceIds: ["deamer-2012"], caveats: ["Membrane composition and permeability are not molecularly resolved."], params: { ...baseEarlyEarth, waterInventory: .68, landFraction: .28 }, origin: { theory: "lipid-first", energy: .5, catalysts: .55, wetDryCycling: .86 }, interventions: [] }),
  scenario({ id: "spark-ice-eutectic", label: "Spark: ice eutectic pockets", subtitle: "Freeze concentration + molecular shelter", description: "Tests cold brine films that concentrate solutes and protect fragile polymers while bulk water freezes.", category: "plausible", evidence: "speculative", modelFit: "native", confidenceNote: "Freeze concentration is physical; relevance to a complete origin pathway is uncertain.", tags: ["origin theory", "ice", "RNA"], sourceIds: ["attwater-2010"], caveats: ["Brine salinity and eutectic phase behavior are represented by a concentration proxy."], params: { ...baseEarlyEarth, starLuminositySolar: .68, orbitalDistanceAu: 1.08, albedo: .46, waterInventory: .92 }, origin: { theory: "ice-eutectic", energy: .34, catalysts: .58, wetDryCycling: .08 }, interventions: [organics(120, .45)] }),
  scenario({ id: "spark-exogenous-feedstock", label: "Spark overlay: exogenous organics", subtitle: "Delivery, not a complete abiogenesis theory", description: "Repeated carbonaceous impacts deliver diverse organic feedstocks into a planet whose local chemistry must still cross all six origin gates.", category: "plausible", evidence: "grounded", modelFit: "native", confidenceNote: "Meteorite organics are measured; their net contribution and survival on early Earth are uncertain.", tags: ["delivery", "meteorites", "feedstock"], sourceIds: ["callahan-2011"], caveats: ["This supplies ingredients; it does not explain self-replication by itself."], params: { ...baseEarlyEarth, impactRate: .78 }, origin: { theory: "exogenous", exogenousDose: .94, recurrence: .82, survivalFraction: .03 }, interventions: [organics(25, .8), organics(95, .72), comet(240, .45)] }),

  scenario({ id: "circumbinary-shore", label: "Circumbinary pulse shore", subtitle: "Two-star irradiation proxy", description: "A shoreline world orbiting a close stellar pair, with combined spectral forcing, moderate irradiation variability, and an origin experiment driven by repeated wet–dry cycles.", category: "experimental", evidence: "coarse", modelFit: "proxy", confidenceNote: "Combined flux is modeled; long-term N-body orbital stability is not integrated.", tags: ["binary", "shoreline", "variable flux"], sourceIds: ["cukier-2019", "kane-2013"], caveats: ["Companion forcing is time-averaged and is not an orbital solution.", "A real circumbinary configuration requires dedicated stability analysis."], params: { ...baseEarlyEarth, starCount: 2, starTopology: "circumbinary", starMassSolar: .86, starLuminositySolar: .58, starTemperatureK: 5200, companionMassSolar: .62, companionLuminositySolar: .16, companionTemperatureK: 4100, companionDistanceAu: 1.65, companionVariability: .38, orbitalDistanceAu: 1.05, orbitalEccentricity: .08 }, origin: { theory: "pond", wetDryCycling: .88, energy: .82 }, interventions: [] }),
  scenario({ id: "triple-pulse-world", label: "Hierarchical triple pulse world", subtitle: "Exploratory aggregate-forcing boundary", description: "A temperate candidate with two representative companion stars and strong time-variable forcing, designed to expose climate-buffer limits.", category: "experimental", evidence: "speculative", modelFit: "proxy", confidenceNote: "This is an aggregate irradiation stress test, not a dynamically solved triple system.", tags: ["triple star", "forcing", "stress test"], sourceIds: ["cukier-2019"], caveats: ["Both companions share one representative parameter set.", "N-body dynamics and eclipses are outside this model."], params: { ...baseEarlyEarth, starCount: 3, starTopology: "hierarchical-triple", starMassSolar: .74, starLuminositySolar: .29, starTemperatureK: 4700, companionMassSolar: .38, companionLuminositySolar: .035, companionTemperatureK: 3450, companionDistanceAu: 1.3, companionVariability: .78, orbitalDistanceAu: .68, orbitalEccentricity: .12, atmospherePressureBar: 1.8, waterInventory: .8 }, origin: { theory: "mineral-template", catalysts: .85 }, interventions: [] }),
  scenario({ id: "active-m-terminator", label: "Active M-dwarf terminator ocean", subtitle: "Flare-exposed close-orbit experiment", description: "A dense-atmosphere ocean world around a young active red dwarf, testing atmospheric retention, tidal rotation, flare stress, and sheltered chemistry.", category: "experimental", evidence: "coarse", modelFit: "proxy", confidenceNote: "Mean climate and escape proxies are available; synchronous-circulation geography is not.", tags: ["M dwarf", "tidal", "flare"], sourceIds: ["kopparapu-2014"], caveats: ["Terminator habitability requires three-dimensional climate modeling.", "Flare spectra are compressed into an activity index."], params: { ...DEFAULT_PARAMS, seed: "", starMassSolar: .29, starLuminositySolar: .012, starTemperatureK: 3250, starActivity: .95, starAgeGyr: .8, orbitalDistanceAu: .11, orbitalEccentricity: .035, rotationHours: 420, atmospherePressureBar: 2.8, atmosphere: anoxic, waterInventory: 1.1, landFraction: .05, coreFraction: .37, mantleFraction: .6, initialHeat: .72, elementBasis: DEFAULT_ELEMENTS }, origin: { theory: "hydrothermal", ventFlux: .92, wetDryCycling: .02 }, interventions: [{ type: "quiet-star", label: "Extended quiet-star interval", scheduledAgeMyr: 300, magnitude: .7, cargo: {} }] }),
  scenario({ id: "old-k-super-earth", label: "Old K-dwarf super-Earth", subtitle: "Long-lived temperate laboratory", description: "A massive rocky world around a quieter orange dwarf, with strong atmospheric retention and a prolonged evolutionary window.", category: "experimental", evidence: "coarse", modelFit: "native", confidenceNote: "Bulk scaling is defensible; super-Earth tectonics and atmosphere evolution remain uncertain.", tags: ["K dwarf", "super-Earth", "long-lived"], sourceIds: ["kopparapu-2014"], caveats: ["Mass–radius combinations are user-set rather than derived from an interior equation of state."], params: { ...DEFAULT_PARAMS, seed: "", starMassSolar: .72, starLuminositySolar: .24, starTemperatureK: 4650, starActivity: .11, starAgeGyr: 6.8, orbitalDistanceAu: .53, planetMassEarth: 2.4, planetRadiusEarth: 1.32, rotationHours: 31, atmospherePressureBar: 2.1, atmosphere: anoxic, waterInventory: .68, landFraction: .38, coreFraction: .31, mantleFraction: .66, initialHeat: .55, radionuclides: .58, elementBasis: DEFAULT_ELEMENTS }, origin: { theory: "mineral-template", catalysts: .78 }, interventions: [] }),
  scenario({ id: "hycean-h2-ocean", label: "Hydrogen-rich Hycean analogue", subtitle: "High-pressure ocean boundary case", description: "A warm sub-Neptune-scale ocean world with a hydrogen-rich envelope, exploring extended liquid-water conditions and atmospheric chemistry.", category: "experimental", evidence: "speculative", modelFit: "proxy", confidenceNote: "Hycean habitability is a published hypothesis; this engine cannot resolve deep-envelope pressure or ocean–mantle isolation.", tags: ["Hycean", "hydrogen", "ocean"], sourceIds: ["madhusudhan-2021", "pierrehumbert-2011"], caveats: ["The 20-bar engine ceiling is far below many proposed Hycean envelopes.", "A global ocean weakens modeled wet–dry chemistry and nutrient recycling."], params: { ...DEFAULT_PARAMS, seed: "", starMassSolar: .62, starLuminositySolar: .12, starTemperatureK: 4100, starAgeGyr: 3.4, orbitalDistanceAu: .41, planetMassEarth: 4.6, planetRadiusEarth: 1.85, atmospherePressureBar: 18, atmosphere: h2Rich, waterInventory: 1.48, landFraction: .002, albedo: .28, coreFraction: .22, mantleFraction: .54, initialHeat: .64, elementBasis: DEFAULT_ELEMENTS }, origin: { theory: "hydrothermal", ventFlux: .9, wetDryCycling: 0 }, interventions: [] }),
  scenario({ id: "carbon-volcanic", label: "Carbon-rich volcanic world", subtitle: "Atypical feedstock inventory", description: "An iron–sulfur active planet with unusually carbon-rich accessible reservoirs and a mineral-template origin experiment.", category: "experimental", evidence: "speculative", modelFit: "proxy", confidenceNote: "Carbon-rich rocky planets are theoretical; mineralogy and solvent behavior are not solved here.", tags: ["carbon-rich", "volcanic", "minerals"], sourceIds: ["lambert-2010"], caveats: ["Element sliders represent bioavailable reservoirs, not bulk elemental abundance.", "Earth-like aqueous polymer rules remain in use."], params: { ...baseEarlyEarth, atmospherePressureBar: 3.2, atmosphere: { ...anoxic, co2: .31, n2: .56, ch4: .07 }, elementBasis: carbonRich, initialHeat: .96, tectonicMobility: .22, coreFraction: .42, mantleFraction: .55, waterInventory: .38, landFraction: .6 }, origin: { theory: "mineral-template", catalysts: .96, ventFlux: .72, wetDryCycling: .78 }, interventions: [] }),
  scenario({ id: "outer-h2-ice-ocean", label: "Outer-zone hydrogen ice ocean", subtitle: "Beyond classical surface-water HZ", description: "An outer-zone world where collision-induced hydrogen greenhouse warming and internal heat maintain a marginal ocean beneath seasonal or persistent ice.", category: "experimental", evidence: "speculative", modelFit: "proxy", confidenceNote: "Hydrogen greenhouse extension is published; subsurface circulation and ice-shell transport are not modeled.", tags: ["outer zone", "hydrogen", "ice ocean"], sourceIds: ["pierrehumbert-2011", "kopparapu-2014"], caveats: ["Conventional habitable-zone status is contextual, not a binary verdict.", "Ice-shell exchange is compressed into hydrothermal activity."], params: { ...baseEarlyEarth, orbitalDistanceAu: 1.65, atmospherePressureBar: 8, atmosphere: h2Rich, albedo: .5, waterInventory: 1.25, landFraction: .01, initialHeat: .9, radionuclides: .88 }, origin: { theory: "ice-eutectic", ventFlux: .8, wetDryCycling: 0 }, interventions: [] }),
  scenario({ id: "cryogenic-methane-boundary", label: "Cryogenic methane boundary case", subtitle: "Deliberately outside aqueous model validity", description: "A Titan-like cold organic world for testing delivery and inventory bookkeeping while exposing where the water–carbon engine ceases to be scientifically interpretable.", category: "experimental", evidence: "speculative", modelFit: "outside-model", confidenceNote: "Organic chemistry is plausible; methane-solvent life and its kinetics remain hypothetical and are not implemented.", tags: ["methane", "cryogenic", "model boundary"], sourceIds: ["callahan-2011"], caveats: ["Abiogenesis and habitability scores are invalid for a methane solvent.", "Use this as an explicit model-boundary demonstration, not a prediction."], params: { ...DEFAULT_PARAMS, seed: "", biochemistryMode: "unsupported-alternative", starMassSolar: .8, starLuminositySolar: .38, starTemperatureK: 4900, starAgeGyr: 4.5, orbitalDistanceAu: 2.9, atmospherePressureBar: 1.6, atmosphere: methaneRich, albedo: .24, waterInventory: .12, landFraction: .82, coreFraction: .28, mantleFraction: .68, initialHeat: .4, elementBasis: carbonRich }, origin: { theory: "custom", energy: .25, catalysts: .35, wetDryCycling: .1 }, interventions: [organics(50, .7)] })
];

export function getScenario(id: string): ScenarioDefinition {
  return SCENARIO_PRESETS.find((item) => item.id === id) ?? SCENARIO_PRESETS[1];
}

export function scenarioConfiguration(definition: ScenarioDefinition, seed: string): ScenarioConfiguration {
  const params = normalizeParams({ ...DEFAULT_PARAMS, ...definition.params, seed, atmosphere: definition.params.atmosphere ?? DEFAULT_PARAMS.atmosphere, elementBasis: definition.params.elementBasis ?? DEFAULT_ELEMENTS });
  return {
    seed,
    params,
    origin: { ...DEFAULT_ORIGIN, ...definition.origin } as OriginConfig,
    interventions: structuredClone(definition.interventions),
    runHorizonMyr: 4500
  };
}

export const ORIGIN_SCENARIOS = SCENARIO_PRESETS.filter((item) => item.id.startsWith("spark-"));
